### ISSUE TITLE
Informations par rapport au fichier MatVolat

### ISSUE THREAD

**Issue by abenc** [bechirbenhassine/Sprint_2_Fil_Rouge#7]
[https://github.com/bechirbenhassine/Sprint_2_Fil_Rouge/blob/MatVolat/MatVolat%20CSV.csv](url)
Quels sont les sous-jacent en question? 
Le fichier contient-il la volatilité implicite ou alors le prix des options?
Le prix des sous-jacent ? 
Le type d'options observée ? (call put forward ?)

**Comment by bechirbenhassine** [comment]
Quels sont les sous-jacent en question?
**Il n'y a aucune information sur le fichier qui indique le type du sous-jacent, lors de la réunion avec S.N. il a mentionné l'expression prix de l'action donc ca peut être des actions (on va se baser sur le retour de C.M.B. pour avoir plus d'information vu que j'ai pas reçu un retour de mail de S.N.)**
Le fichier contient-il la volatilité implicite ou alors le prix des options?
**Le fichier contient en ligne les strikes qui sont les prix d'exercice des options ainsi que la volatilité implicite en données (tu peux remarquer qu'en fixant la maturité il y a une augmentation de la volatilité implicite au fur et à mesure que son prix d'exercice est éloigné du prix du sous-jacent d'où la fomre de smile de volatilité)**
Le prix des sous-jacent ?
**Comme expliqué, quand tu dresse le smile de volatilité, le minimum de la courbe représenterait le prix du sous-jacent puisque la règle dit que la volatilité implicite augmente si le prix de l'option s'éloigne à la hausse ou la baisse du prix du sous-jacent**
Le type d'options observée ? (call put forward ?)
**En fait une option consiste en un put ou un call. Un forward est différent des options car le détenteur d'un forward est dans l'obligation de l'exercer à maturité alors que l'option le détenteur à le libre choix**
